{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: frigate
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ git_revision_count }}
  script: python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  build:
    - python >=3
    - setuptools
    - click
    - docutils
    - jinja2
    - ruamel.yaml
  run:
    - python >=3
    - click
    - docutils
    - jinja2
    - ruamel.yaml


test:
  imports:
    - frigate

about:
  home: https://rapids.ai
  license: Apache
  summary: 'A tool for autogenerating helm documentation'
  dev_url: https://github.com/rapidsai/frigate
